import type { GameState, AgentThought } from '../engine/types';

export const AGENT_COLORS: Record<string, string> = {
  claude: '#D4A574',
  'gpt-4o': '#74AA9C',
  gemini: '#4285F4',
  grok: '#FF6B35',
  deepseek: '#00BCD4',
  llama: '#9C27B0',
};

export const mockGameState: GameState = {
  handNumber: 7,
  round: 'flop',
  communityCards: [
    { rank: 'A', suit: 'spades' },
    { rank: 'K', suit: 'hearts' },
    { rank: '9', suit: 'diamonds' },
  ],
  pots: [{ amount: 1200, eligiblePlayerIds: ['claude', 'gpt-4o', 'gemini', 'grok', 'deepseek', 'llama'] }],
  currentPlayerId: 'gpt-4o',
  dealerIndex: 0,
  blinds: { small: 50, big: 100 },
  isGameOver: false,
  players: [
    {
      id: 'claude',
      name: 'Claude',
      provider: 'anthropic',
      model: 'claude-sonnet-4-5-20250514',
      chips: 9400,
      holeCards: [{ rank: 'A', suit: 'hearts' }, { rank: 'Q', suit: 'spades' }],
      currentBet: 200,
      isFolded: false,
      isAllIn: false,
      isEliminated: false,
      isBotFallback: false,
      seatIndex: 0,
      lastAction: { action: 'raise', amount: 200, reasoning: 'Top pair with a strong kicker. I want to build the pot while I likely have the best hand.', latencyMs: 1240 },
      color: AGENT_COLORS.claude,
    },
    {
      id: 'gpt-4o',
      name: 'GPT-4o',
      provider: 'openai',
      model: 'gpt-4o',
      chips: 9800,
      holeCards: [{ rank: 'K', suit: 'clubs' }, { rank: 'J', suit: 'clubs' }],
      currentBet: 0,
      isFolded: false,
      isAllIn: false,
      isEliminated: false,
      isBotFallback: false,
      seatIndex: 1,
      lastAction: null,
      color: AGENT_COLORS['gpt-4o'],
    },
    {
      id: 'gemini',
      name: 'Gemini',
      provider: 'google',
      model: 'gemini-2.5-pro',
      chips: 10200,
      holeCards: [{ rank: '7', suit: 'hearts' }, { rank: '7', suit: 'diamonds' }],
      currentBet: 200,
      isFolded: false,
      isAllIn: false,
      isEliminated: false,
      isBotFallback: false,
      seatIndex: 2,
      lastAction: { action: 'call', reasoning: 'Mid pair, decent implied odds. I can reevaluate on the turn.', latencyMs: 890 },
      color: AGENT_COLORS.gemini,
    },
    {
      id: 'grok',
      name: 'Grok',
      provider: 'xai',
      model: 'grok-3',
      chips: 8900,
      holeCards: [{ rank: '5', suit: 'spades' }, { rank: '3', suit: 'spades' }],
      currentBet: 0,
      isFolded: true,
      isAllIn: false,
      isEliminated: false,
      isBotFallback: false,
      seatIndex: 3,
      lastAction: { action: 'fold', reasoning: 'Even I know when to walk away. This board is too wet for my garbage hand. Live to fight another day!', latencyMs: 650 },
      color: AGENT_COLORS.grok,
    },
    {
      id: 'deepseek',
      name: 'DeepSeek',
      provider: 'deepseek',
      model: 'deepseek-chat',
      chips: 11500,
      holeCards: [{ rank: '10', suit: 'hearts' }, { rank: '10', suit: 'clubs' }],
      currentBet: 200,
      isFolded: false,
      isAllIn: false,
      isEliminated: false,
      isBotFallback: false,
      seatIndex: 4,
      lastAction: { action: 'call', reasoning: 'Pot odds of 6:1 justify a call with my pocket tens. Probability of improving to a set on turn is ~4.3%.', latencyMs: 1100 },
      color: AGENT_COLORS.deepseek,
    },
    {
      id: 'llama',
      name: 'Llama',
      provider: 'groq',
      model: 'llama-3.3-70b',
      chips: 0,
      holeCards: [],
      currentBet: 0,
      isFolded: false,
      isAllIn: false,
      isEliminated: true,
      isBotFallback: false,
      seatIndex: 5,
      lastAction: null,
      color: AGENT_COLORS.llama,
    },
  ],
};

export const mockThoughts: AgentThought[] = [
  {
    playerId: 'grok',
    playerName: 'Grok',
    reasoning: 'Even I know when to walk away. This board is too wet for my garbage hand. Live to fight another day!',
    action: { action: 'fold', reasoning: '', latencyMs: 650 },
    handNumber: 7,
    round: 'flop',
    timestamp: Date.now() - 12000,
  },
  {
    playerId: 'deepseek',
    playerName: 'DeepSeek',
    reasoning: 'Pot odds of 6:1 justify a call with my pocket tens. Probability of improving to a set on turn is approximately 4.3%. Expected value is positive.',
    action: { action: 'call', reasoning: '', latencyMs: 1100 },
    handNumber: 7,
    round: 'flop',
    timestamp: Date.now() - 9000,
  },
  {
    playerId: 'claude',
    playerName: 'Claude',
    reasoning: 'Top pair with a strong kicker on a relatively dry board. I want to build the pot while I likely have the best hand. A raise to $200 prices out draws while keeping weaker made hands in.',
    action: { action: 'raise', amount: 200, reasoning: '', latencyMs: 1240 },
    handNumber: 7,
    round: 'flop',
    timestamp: Date.now() - 6000,
  },
  {
    playerId: 'gemini',
    playerName: 'Gemini',
    reasoning: 'Mid pair with decent implied odds. The raise is small relative to the pot, so I can profitably call and reevaluate on the turn. If I hit my set, I can extract maximum value.',
    action: { action: 'call', reasoning: '', latencyMs: 890 },
    handNumber: 7,
    round: 'flop',
    timestamp: Date.now() - 3000,
  },
];
